-- ============================================================================
-- BCSS Stats - Oracle Indexes (Staging)
-- ============================================================================

-- StatCategories
CREATE INDEX IX_STAT_CAT_GROUP_ID ON STAT_CATEGORIES (GROUP_ID);

-- SubCategories
CREATE INDEX IX_SUB_CAT_CATEGORY_ID ON SUB_CATEGORIES (CATEGORY_ID);

-- SubCategoryMetrics
CREATE INDEX IX_SCM_SUB_CATEGORY_ID ON SUB_CATEGORY_METRICS (SUB_CATEGORY_ID);
CREATE INDEX IX_SCM_METRIC_ID ON SUB_CATEGORY_METRICS (METRIC_ID);

-- StatRecords
CREATE INDEX IX_STAT_REC_LOCATION_ID ON STAT_RECORDS (LOCATION_ID);
CREATE INDEX IX_STAT_REC_SCM_ID ON STAT_RECORDS (SUB_CATEGORY_METRIC_ID);
CREATE INDEX IX_STAT_REC_DATE_RANGE ON STAT_RECORDS (DATE_FROM, DATE_TO);
CREATE INDEX IX_STAT_REC_USER_ID ON STAT_RECORDS (USER_ID);
CREATE INDEX IX_STAT_REC_STATUS ON STAT_RECORDS (STATUS);

-- StatSignoffs
CREATE INDEX IX_STAT_SO_LOCATION_ID ON STAT_SIGNOFFS (LOCATION_ID);
CREATE INDEX IX_STAT_SO_USER_ID ON STAT_SIGNOFFS (USER_ID);
